<Label>:
    color: (0, 0, 0, 1)
<Button>:
    background_color: (.9, .9, .9, 1)
    background_normal: ""
<TextInput>:
    background_color: (.97, .97, .97, 1)
    background_normal: ""
BoxLayout:
    background_color: (1, 1, 1, 1)
    id: root_widget
    orientation: "vertical"
    size_hint: (1, 1)
    canvas:
        Color:
            rgba: root.background_color
        Rectangle:
            pos: self.pos
            size: self.size
